name: photogrammetry
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ninja
  - cmake
  - gcc_linux-64
  - gxx_linux-64
  - pip
